---
name: Google-Data-JSON
version: v0.0.2
author:
  - 'Takeru INOUE <takeru.inoue@gmail.com>'
abstract: XML-JSON converter based on Google Data APIs
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  JSON: 0
  Path::Class: 0
  Storable: 0
  Test::More: 0
  Test::NoWarnings: 0
  Test::Perl::Critic: 0
  UNIVERSAL::require: 0
  XML::Atom: 0
  XML::Simple: 0
  version: 0
provides:
  Google::Data::JSON:
    file: lib/Google/Data/JSON.pm
    version: v0.0.2
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
